"""
Board-wise syllabus data: Board → Class → Subject → Chapters
Used by the MCQ generator to populate dropdowns and validate inputs.
"""

BOARDS_DATA = {
    "CBSE": {
        "Class 8": {
            "Mathematics": [
                "Rational Numbers",
                "Linear Equations in One Variable",
                "Understanding Quadrilaterals",
                "Data Handling",
                "Squares and Square Roots",
                "Cubes and Cube Roots",
                "Comparing Quantities",
                "Algebraic Expressions and Identities",
                "Mensuration",
                "Exponents and Powers",
                "Direct and Inverse Proportions",
                "Factorisation",
                "Introduction to Graphs",
                "Playing with Numbers"
            ],
            "Science": [
                "Crop Production and Management",
                "Microorganisms: Friend and Foe",
                "Synthetic Fibres and Plastics",
                "Materials: Metals and Non-Metals",
                "Coal and Petroleum",
                "Combustion and Flame",
                "Conservation of Plants and Animals",
                "Cell: Structure and Functions",
                "Reproduction in Animals",
                "Force and Pressure",
                "Friction",
                "Sound",
                "Chemical Effects of Electric Current",
                "Some Natural Phenomena",
                "Light",
                "Stars and the Solar System",
                "Pollution of Air and Water"
            ],
            "Social Science": [
                "How, When and Where",
                "From Trade to Territory",
                "Ruling the Countryside",
                "Tribals, Dikus and the Vision of a Golden Age",
                "When People Rebel",
                "The Indian Constitution",
                "Understanding Secularism",
                "Resources",
                "Land, Soil, Water, Natural Vegetation and Wildlife Resources",
                "Industries"
            ]
        },
        "Class 9": {
            "Mathematics": [
                "Number Systems",
                "Polynomials",
                "Coordinate Geometry",
                "Linear Equations in Two Variables",
                "Introduction to Euclid's Geometry",
                "Lines and Angles",
                "Triangles",
                "Quadrilaterals",
                "Circles",
                "Heron's Formula",
                "Surface Areas and Volumes",
                "Statistics",
                "Probability"
            ],
            "Science": [
                "Matter in Our Surroundings",
                "Is Matter Around Us Pure?",
                "Atoms and Molecules",
                "Structure of the Atom",
                "The Fundamental Unit of Life",
                "Tissues",
                "Motion",
                "Force and Laws of Motion",
                "Gravitation",
                "Work and Energy",
                "Sound",
                "Improvement in Food Resources"
            ],
            "Social Science": [
                "The French Revolution",
                "Socialism in Europe and the Russian Revolution",
                "Nazism and the Rise of Hitler",
                "India – Size and Location",
                "Physical Features of India",
                "Drainage",
                "Climate",
                "Natural Vegetation and Wildlife",
                "Democracy in the Contemporary World",
                "Constitutional Design",
                "Electoral Politics",
                "Working of Institutions",
                "The Story of Village Palampur",
                "People as Resource",
                "Poverty as a Challenge"
            ]
        },
        "Class 10": {
            "Mathematics": [
                "Real Numbers",
                "Polynomials",
                "Pair of Linear Equations in Two Variables",
                "Quadratic Equations",
                "Arithmetic Progressions",
                "Triangles",
                "Coordinate Geometry",
                "Introduction to Trigonometry",
                "Some Applications of Trigonometry",
                "Circles",
                "Areas Related to Circles",
                "Surface Areas and Volumes",
                "Statistics",
                "Probability"
            ],
            "Science": [
                "Chemical Reactions and Equations",
                "Acids, Bases and Salts",
                "Metals and Non-metals",
                "Carbon and its Compounds",
                "Life Processes",
                "Control and Coordination",
                "How do Organisms Reproduce?",
                "Heredity and Evolution",
                "Light – Reflection and Refraction",
                "The Human Eye and the Colourful World",
                "Electricity",
                "Magnetic Effects of Electric Current",
                "Our Environment"
            ],
            "Social Science": [
                "The Rise of Nationalism in Europe",
                "Nationalism in India",
                "The Making of a Global World",
                "The Age of Industrialisation",
                "Resources and Development",
                "Water Resources",
                "Agriculture",
                "Minerals and Energy Resources",
                "Manufacturing Industries",
                "Power Sharing",
                "Federalism",
                "Democracy and Diversity",
                "Gender, Religion and Caste",
                "Money and Credit",
                "Globalisation and the Indian Economy"
            ],
            "English": [
                "A Letter to God",
                "Nelson Mandela: Long Walk to Freedom",
                "Two Stories about Flying",
                "From the Diary of Anne Frank",
                "Glimpses of India",
                "A Triumph of Surgery",
                "The Thief's Story",
                "Footprints without Feet",
                "The Hack Driver",
                "Bholi"
            ]
        },
        "Class 11": {
            "Physics": [
                "Physical World",
                "Units and Measurements",
                "Motion in a Straight Line",
                "Motion in a Plane",
                "Laws of Motion",
                "Work, Energy and Power",
                "System of Particles and Rotational Motion",
                "Gravitation",
                "Mechanical Properties of Solids",
                "Mechanical Properties of Fluids",
                "Thermal Properties of Matter",
                "Thermodynamics",
                "Kinetic Theory",
                "Oscillations",
                "Waves"
            ],
            "Chemistry": [
                "Some Basic Concepts of Chemistry",
                "Structure of Atom",
                "Classification of Elements and Periodicity",
                "Chemical Bonding and Molecular Structure",
                "Thermodynamics",
                "Equilibrium",
                "Redox Reactions",
                "Organic Chemistry: Some Basic Principles",
                "Hydrocarbons",
                "The s-Block Elements",
                "The p-Block Elements",
                "Environmental Chemistry"
            ],
            "Mathematics": [
                "Sets",
                "Relations and Functions",
                "Trigonometric Functions",
                "Complex Numbers and Quadratic Equations",
                "Linear Inequalities",
                "Permutations and Combinations",
                "Binomial Theorem",
                "Sequences and Series",
                "Straight Lines",
                "Conic Sections",
                "Introduction to Three-Dimensional Geometry",
                "Limits and Derivatives",
                "Statistics",
                "Probability"
            ],
            "Biology": [
                "The Living World",
                "Biological Classification",
                "Plant Kingdom",
                "Animal Kingdom",
                "Morphology of Flowering Plants",
                "Anatomy of Flowering Plants",
                "Cell: The Unit of Life",
                "Biomolecules",
                "Cell Cycle and Cell Division",
                "Photosynthesis in Higher Plants",
                "Respiration in Plants",
                "Plant Growth and Development",
                "Breathing and Exchange of Gases",
                "Body Fluids and Circulation",
                "Excretory Products and Their Elimination",
                "Locomotion and Movement",
                "Neural Control and Coordination",
                "Chemical Coordination and Integration"
            ]
        },
        "Class 12": {
            "Physics": [
                "Electric Charges and Fields",
                "Electrostatic Potential and Capacitance",
                "Current Electricity",
                "Moving Charges and Magnetism",
                "Magnetism and Matter",
                "Electromagnetic Induction",
                "Alternating Current",
                "Electromagnetic Waves",
                "Ray Optics and Optical Instruments",
                "Wave Optics",
                "Dual Nature of Radiation and Matter",
                "Atoms",
                "Nuclei",
                "Semiconductor Electronics"
            ],
            "Chemistry": [
                "The Solid State",
                "Solutions",
                "Electrochemistry",
                "Chemical Kinetics",
                "Surface Chemistry",
                "Isolation of Elements",
                "The p-Block Elements",
                "The d- and f-Block Elements",
                "Coordination Compounds",
                "Haloalkanes and Haloarenes",
                "Alcohols, Phenols and Ethers",
                "Aldehydes, Ketones and Carboxylic Acids",
                "Amines",
                "Biomolecules",
                "Polymers",
                "Chemistry in Everyday Life"
            ],
            "Mathematics": [
                "Relations and Functions",
                "Inverse Trigonometric Functions",
                "Matrices",
                "Determinants",
                "Continuity and Differentiability",
                "Application of Derivatives",
                "Integrals",
                "Application of Integrals",
                "Differential Equations",
                "Vector Algebra",
                "Three Dimensional Geometry",
                "Linear Programming",
                "Probability"
            ],
            "Biology": [
                "Reproduction in Organisms",
                "Sexual Reproduction in Flowering Plants",
                "Human Reproduction",
                "Reproductive Health",
                "Principles of Inheritance and Variation",
                "Molecular Basis of Inheritance",
                "Evolution",
                "Human Health and Disease",
                "Strategies for Enhancement in Food Production",
                "Microbes in Human Welfare",
                "Biotechnology: Principles and Processes",
                "Biotechnology and Its Applications",
                "Organisms and Populations",
                "Ecosystem",
                "Biodiversity and Conservation",
                "Environmental Issues"
            ]
        }
    },
    "ICSE": {
        "Class 10": {
            "Mathematics": [
                "GST (Goods and Services Tax)",
                "Banking",
                "Shares and Dividends",
                "Linear Inequations",
                "Quadratic Equations",
                "Ratio and Proportion",
                "Factorisation of Polynomials",
                "Matrices",
                "Arithmetic Progression",
                "Coordinate Geometry",
                "Similarity",
                "Loci",
                "Circles",
                "Constructions",
                "Mensuration",
                "Trigonometry",
                "Statistics",
                "Probability"
            ],
            "Physics": [
                "Force, Work, Power and Energy",
                "Machines",
                "Refraction of Light",
                "Lenses",
                "Spectrum",
                "Sound",
                "Current Electricity",
                "Electrical Power and Household Circuits",
                "Electro-Magnetism",
                "Calorimetry",
                "Radioactivity and Nuclear Energy"
            ],
            "Chemistry": [
                "Periodic Table and Periodicity",
                "Chemical Bonding",
                "Acids, Bases and Salts",
                "Analytical Chemistry",
                "Mole Concept",
                "Electrolysis",
                "Metallurgy",
                "Study of Compounds: Hydrogen Chloride",
                "Study of Compounds: Ammonia",
                "Study of Compounds: Nitric Acid",
                "Study of Compounds: Sulphuric Acid",
                "Organic Chemistry"
            ],
            "Biology": [
                "Cell Division",
                "Genetics",
                "Absorption by Roots",
                "Transpiration",
                "Photosynthesis",
                "Chemical Coordination in Plants",
                "The Circulatory System",
                "The Excretory System",
                "The Nervous System",
                "The Reproductive System",
                "Population",
                "Pollution"
            ]
        }
    },
    "Maharashtra Board": {
        "Class 8": {
            "Mathematics": [
                "Rational Numbers",
                "Linear Equations in One Variable",
                "Understanding Quadrilaterals",
                "Data Handling",
                "Squares and Square Roots",
                "Cubes and Cube Roots",
                "Comparing Quantities",
                "Algebraic Expressions and Identities",
                "Mensuration",
                "Exponents and Powers",
                "Direct and Inverse Proportions",
                "Factorisation",
                "Introduction to Graphs",
                "Playing with Numbers"
            ],
            "Science": [
                "Crop Production and Management",
                "Microorganisms: Friend and Foe",
                "Synthetic Fibres and Plastics",
                "Materials: Metals and Non-Metals",
                "Coal and Petroleum",
                "Combustion and Flame",
                "Conservation of Plants and Animals",
                "Cell: Structure and Functions",
                "Reproduction in Animals",
                "Force and Pressure",
                "Friction",
                "Sound",
                "Chemical Effects of Electric Current",
                "Some Natural Phenomena",
                "Light",
                "Stars and the Solar System",
                "Pollution of Air and Water"
            ],
            "Social Science": [
                "How, When and Where",
                "From Trade to Territory",
                "Ruling the Countryside",
                "Tribals, Dikus and the Vision of a Golden Age",
                "When People Rebel",
                "The Indian Constitution",
                "Understanding Secularism",
                "Resources",
                "Land, Soil, Water, Natural Vegetation and Wildlife Resources",
                "Industries"
            ]
        },
        "Class 9": {
            "Mathematics": [
                "Number Systems",
                "Polynomials",
                "Coordinate Geometry",
                "Linear Equations in Two Variables",
                "Introduction to Euclid's Geometry",
                "Lines and Angles",
                "Triangles",
                "Quadrilaterals",
                "Circles",
                "Heron's Formula",
                "Surface Areas and Volumes",
                "Statistics",
                "Probability"
            ],
            "Science": [
                "Matter in Our Surroundings",
                "Is Matter Around Us Pure?",
                "Atoms and Molecules",
                "Structure of the Atom",
                "The Fundamental Unit of Life",
                "Tissues",
                "Motion",
                "Force and Laws of Motion",
                "Gravitation",
                "Work and Energy",
                "Sound",
                "Improvement in Food Resources"
            ],
            "Social Science": [
                "The French Revolution",
                "Socialism in Europe and the Russian Revolution",
                "Nazism and the Rise of Hitler",
                "India – Size and Location",
                "Physical Features of India",
                "Drainage",
                "Climate",
                "Natural Vegetation and Wildlife",
                "Democracy in the Contemporary World",
                "Constitutional Design",
                "Electoral Politics",
                "Working of Institutions",
                "The Story of Village Palampur",
                "People as Resource",
                "Poverty as a Challenge"
            ]
        },
        "Class 10": {
            "Mathematics": [
                "Real Numbers",
                "Polynomials",
                "Pair of Linear Equations in Two Variables",
                "Quadratic Equations",
                "Arithmetic Progressions",
                "Triangles",
                "Coordinate Geometry",
                "Introduction to Trigonometry",
                "Some Applications of Trigonometry",
                "Circles",
                "Areas Related to Circles",
                "Surface Areas and Volumes",
                "Statistics",
                "Probability"
            ],
            "Science": [
                "Chemical Reactions and Equations",
                "Acids, Bases and Salts",
                "Metals and Non-metals",
                "Carbon and its Compounds",
                "Life Processes",
                "Control and Coordination",
                "How do Organisms Reproduce?",
                "Heredity and Evolution",
                "Light – Reflection and Refraction",
                "The Human Eye and the Colourful World",
                "Electricity",
                "Magnetic Effects of Electric Current",
                "Our Environment"
            ],
            "Social Science": [
                "The Rise of Nationalism in Europe",
                "Nationalism in India",
                "The Making of a Global World",
                "The Age of Industrialisation",
                "Resources and Development",
                "Water Resources",
                "Agriculture",
                "Minerals and Energy Resources",
                "Manufacturing Industries",
                "Power Sharing",
                "Federalism",
                "Democracy and Diversity",
                "Gender, Religion and Caste",
                "Money and Credit",
                "Globalisation and the Indian Economy"
            ],
            "English": [
                "A Letter to God",
                "Nelson Mandela: Long Walk to Freedom",
                "Two Stories about Flying",
                "From the Diary of Anne Frank",
                "Glimpses of India",
                "A Triumph of Surgery",
                "The Thief's Story",
                "Footprints without Feet",
                "The Hack Driver",
                "Bholi"
            ]
        },
        "Class 12": {
            "Physics": [
                "Rotational Dynamics",
                "Mechanical Properties of Fluids",
                "Kinetic Theory of Gases and Radiation",
                "Thermodynamics",
                "Oscillations",
                "Superposition of Waves",
                "Wave Optics",
                "Electrostatics",
                "Current Electricity",
                "Magnetic Fields due to Electric Current",
                "Magnetic Materials",
                "Electromagnetic Induction",
                "AC Circuits",
                "Dual Nature of Radiation and Matter",
                "Structure of Atoms and Nuclei",
                "Semiconductor Devices"
            ],
            "Chemistry": [
                "Solid State",
                "Solutions",
                "Ionic Equilibria",
                "Chemical Thermodynamics",
                "Electrochemistry",
                "Chemical Kinetics",
                "Elements of Groups 15 and 16",
                "Elements of Groups 17 and 18",
                "Transition and Inner Transition Elements",
                "Coordination Compounds",
                "Halogen Derivatives",
                "Alcohols, Phenols and Ethers",
                "Aldehydes, Ketones and Carboxylic Acids",
                "Organic Compounds Containing Nitrogen",
                "Biomolecules",
                "Introduction to Polymer Chemistry"
            ],
            "Mathematics": [
                "Mathematical Logic",
                "Matrices",
                "Trigonometric Functions",
                "Pair of Straight Lines",
                "Vectors",
                "Three Dimensional Geometry",
                "Line",
                "Plane",
                "Linear Programming",
                "Continuity",
                "Differentiation",
                "Applications of Derivatives",
                "Integration",
                "Definite Integration",
                "Application of Definite Integration",
                "Differential Equations",
                "Probability Distribution",
                "Binomial Distribution"
            ],
            "Biology": [
                "Reproduction in Lower and Higher Plants",
                "Reproduction in Lower and Higher Animals",
                "Inheritance and Variation",
                "Molecular Basis of Inheritance",
                "Origin and Evolution of Life",
                "Plant Water Relations",
                "Plant Growth and Mineral Nutrition",
                "Respiration and Circulation",
                "Control and Coordination",
                "Human Health and Diseases",
                "Enhancement of Food Production",
                "Biotechnology",
                "Organisms and Populations",
                "Ecosystems and Energy Flow",
                "Biodiversity, Conservation and Environmental Issues"
            ]
        }
    },
    "UP Board": {
        "Class 10": {
            "Mathematics": [
                "Real Numbers",
                "Polynomials",
                "Pair of Linear Equations in Two Variables",
                "Quadratic Equations",
                "Arithmetic Progressions",
                "Triangles",
                "Coordinate Geometry",
                "Introduction to Trigonometry",
                "Applications of Trigonometry",
                "Circles",
                "Areas Related to Circles",
                "Surface Areas and Volumes",
                "Statistics",
                "Probability"
            ],
            "Science": [
                "Chemical Reactions and Equations",
                "Acids, Bases and Salts",
                "Metals and Non-metals",
                "Carbon and its Compounds",
                "Life Processes",
                "Control and Coordination",
                "Reproduction",
                "Heredity and Evolution",
                "Light – Reflection and Refraction",
                "Human Eye and Colourful World",
                "Electricity",
                "Magnetic Effects of Electric Current",
                "Our Environment"
            ]
        },
        "Class 12": {
            "Physics": [
                "Electric Charges and Fields",
                "Electrostatic Potential and Capacitance",
                "Current Electricity",
                "Moving Charges and Magnetism",
                "Magnetism and Matter",
                "Electromagnetic Induction",
                "Alternating Current",
                "Electromagnetic Waves",
                "Ray Optics",
                "Wave Optics",
                "Dual Nature of Radiation and Matter",
                "Atoms",
                "Nuclei",
                "Semiconductor Electronics",
                "Communication Systems"
            ],
            "Chemistry": [
                "The Solid State",
                "Solutions",
                "Electrochemistry",
                "Chemical Kinetics",
                "Surface Chemistry",
                "Isolation of Elements",
                "The p-Block Elements",
                "The d- and f-Block Elements",
                "Coordination Compounds",
                "Haloalkanes and Haloarenes",
                "Alcohols, Phenols and Ethers",
                "Aldehydes, Ketones and Carboxylic Acids",
                "Amines",
                "Biomolecules"
            ],
            "Mathematics": [
                "Relations and Functions",
                "Inverse Trigonometric Functions",
                "Matrices",
                "Determinants",
                "Continuity and Differentiability",
                "Application of Derivatives",
                "Integrals",
                "Application of Integrals",
                "Differential Equations",
                "Vector Algebra",
                "Three Dimensional Geometry",
                "Linear Programming",
                "Probability"
            ]
        }
    },
    "Bihar Board": {
        "Class 10": {
            "Mathematics": [
                "Real Numbers",
                "Polynomials",
                "Pair of Linear Equations in Two Variables",
                "Quadratic Equations",
                "Arithmetic Progressions",
                "Triangles",
                "Coordinate Geometry",
                "Introduction to Trigonometry",
                "Applications of Trigonometry",
                "Circles",
                "Areas Related to Circles",
                "Surface Areas and Volumes",
                "Statistics",
                "Probability"
            ],
            "Science": [
                "Chemical Reactions and Equations",
                "Acids, Bases and Salts",
                "Metals and Non-metals",
                "Carbon and its Compounds",
                "Life Processes",
                "Control and Coordination",
                "Reproduction",
                "Heredity and Evolution",
                "Light – Reflection and Refraction",
                "Human Eye and Colourful World",
                "Electricity",
                "Magnetic Effects of Electric Current",
                "Our Environment"
            ]
        },
        "Class 12": {
            "Physics": [
                "Electric Charges and Fields",
                "Electrostatic Potential and Capacitance",
                "Current Electricity",
                "Moving Charges and Magnetism",
                "Magnetism and Matter",
                "Electromagnetic Induction",
                "Alternating Current",
                "Electromagnetic Waves",
                "Ray Optics",
                "Wave Optics",
                "Dual Nature of Radiation and Matter",
                "Atoms",
                "Nuclei",
                "Semiconductor Electronics"
            ],
            "Chemistry": [
                "The Solid State",
                "Solutions",
                "Electrochemistry",
                "Chemical Kinetics",
                "Surface Chemistry",
                "Isolation of Elements",
                "The p-Block Elements",
                "The d- and f-Block Elements",
                "Coordination Compounds",
                "Haloalkanes and Haloarenes",
                "Alcohols, Phenols and Ethers",
                "Aldehydes, Ketones and Carboxylic Acids",
                "Amines",
                "Biomolecules"
            ],
            "Mathematics": [
                "Relations and Functions",
                "Inverse Trigonometric Functions",
                "Matrices",
                "Determinants",
                "Continuity and Differentiability",
                "Application of Derivatives",
                "Integrals",
                "Application of Integrals",
                "Differential Equations",
                "Vector Algebra",
                "Three Dimensional Geometry",
                "Linear Programming",
                "Probability"
            ]
        }
    }
}
